### ISSUE TITLE
PCC date

### ISSUE THREAD

**Issue by pmk01** [mrwilson/sopn-publish-date#61]
The date given for PCC SoPNs appears to be incorrect. It's shown as 12th but the legislation/ council timetables suggest it should be 8 or 9 April, along with most other positions. eg:
https://www.reigate-banstead.gov.uk/info/20318/voting_and_elections/726/police_and_crime_commissioner_elections
https://www.uttlesford.gov.uk/article/6119/Timetable-for-the-elections-being-held-on-6-May-2021

**Comment by mrwilson** [comment]
Thanks for flagging this up! I'll take a look.

**Comment by mrwilson** [comment]
For visibility to observers, running this locally using v1.4.3 I get:

```python
from sopn_publish_date import StatementPublishDate 
from datetime import date

StatementPublishDate().police_and_crime_commissioner(date(2021,5,6))

# datetime.date(2021, 4, 9)
```

The date for the Surrey PCC seems to be off by one (the 8th rather than the 9th)

The date for the Essex PFCC isn't shown online, but the deadline for delivery of nomination papers is the 8th (which is consistent as the day after is usually the date of publication)

**Comment by mrwilson** [comment]
It looks like this might be a versioning issue, where a new version of the library (with updated bank holiday data) is not being pulled in by Dependabot.

**Comment by symroe** [comment]
Having updated the library on WhoCanIVoteFor.co.uk this is now showing the correct date. 

I think this means this issue is 'fixed'

**Comment by mrwilson** [comment]
Lovely, will close this then. Thanks @symroe !
